### ISSUE TITLE
Remove mandatory service feature from codebase (already inaccessible for users)

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#421]
Used by SRC, but not needed anymore after migrating from SURF RC org to SURF org.

### Tasks
- [x] Remove all references to organisation.services (including seed and join table)
- [x] Remove all references to organisation.services in the client code base
- [x] Remove the tab services from an organisation (Mandatory for all collaborations)

**Comment by FlorisFokkinga** [comment]
They can connect via the org API.

Context for the 'org AUP' use case: only four organisations have an on-boarding message, two of which are placeholders.

**Comment by baszoetekouw** [comment]
Is currently only used for 2 organizations.  Plan is to remove the functionality form SBS:
 - disable UI so new Orgs can't enable it again
 - migrate current usecases
 - remove functionality from SBS

**Comment by baszoetekouw** [comment]
Need to coordinate with SRC, because they need to use the API to connect SRC to the COs.
Also, need a migration script to convert currenly connected Org Services to CO-connected Services, without reprovisioning all groups.

**Comment by baszoetekouw** [comment]
Zie https://jira.ia.surf.nl/browse/SRAM-162 voor omzetting UU

**Comment by FlorisFokkinga** [comment]
Not used anymore on PROD, can be removed.

**Comment by baszoetekouw** [comment]
@oharsta what is the status of this? Still in progress?

**Comment by oharsta** [comment]
@baszoetekouw Cosily residing in `Todo`. The visual elements are removed, but the actual functionality still exists in the codebase.

**Comment by oharsta** [comment]
Currently working on coverage and started removing parts of the (extended) server code.
